### ISSUE TITLE
Add a few shards

### ISSUE THREAD

**Issue by jwoertink** [andrewmcodes/awesome-lucky#15]
I have a few Lucky shards if you want to add them

https://github.com/jwoertink/lucky-basic-auth

https://github.com/jwoertink/lucky-cluster/

**Comment by andrewmcodes** [comment]
Merged to master - thanks for sharing @jwoertink! 

Keep 'em coming! Your cluster shard is particularly interesting - definitely going to play with it some when I have some free time. Excited to see what you come out with next!
