### ISSUE TITLE
Another shard

### ISSUE THREAD

**Issue by jwoertink** [andrewmcodes/awesome-lucky#17]
I don't know how updated this is, but just came across https://github.com/oneiros/carbon_smtp_adapter

**Comment by jwoertink** [comment]
It does seem that it hasn't been updated in a while, but I haven't tried it. It could possibly still work. I'd say it could still be useful for people to know about. Worst case is someone finds it and goes to use it then sends a PR or reports issues to be updated.

**Comment by andrewmcodes** [comment]
Good deal. I’ll go ahead and add it then :+1:

**Comment by andrewmcodes** [comment]
@jwoertink https://github.com/andrewmcodes/awesome-lucky/pull/18 should wrap this up! Lmk if you have more resources or find an issue!
