### ISSUE TITLE
A bunch of other tutorials and blog posts 

### ISSUE THREAD

**Issue by paulcsmith** [andrewmcodes/awesome-lucky#2]
* https://hackernoon.com/ruby-on-rails-to-lucky-on-crystal-blazing-fast-fewer-bugs-and-even-more-fun-104010913fec
* https://dev.to/jwoertink/google-oauth-with-lucky-5c10
* https://dev.to/jwoertink/xml-sitemaps-with-lucky-2p5g
* https://dev.to/mikeeus/react-components-in-lucky-with-laravel-mix-and-lucky-react-nlb
* https://dev.to/mikeeus/mapping-database-queries-to-crystal-classes-with-crystal-db-and-lucky-460i
* https://dev.to/mikeeus/jwt-auth-in-lucky-api-if0
* https://dev.to/mikeeus/using-materialized-views-as-models-in-lucky-34ne
* https://dev.to/jwoertink/plain-text-pages-in-lucky-27ja
* https://dev.to/jwoertink/themeing-sites-in-lucky-1a4d

**Comment by andrewmcodes** [comment]
👍
