### ISSUE TITLE
Add *Shield*

### ISSUE THREAD

**Issue by akadusei** [andrewmcodes/awesome-lucky#27]
https://github.com/grottopress/shield

**Comment by andrewmcodes** [comment]
Hi @akadusei  👋 

Would you be willing to open a PR to add this? Let me know if I can assist.

**Comment by akadusei** [comment]
> Hi @akadusei wave
> 
> Would you be willing to open a PR to add this? Let me know if I can assist.

Sure. I'll get to it as soon as I'm able. Thanks.
