### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jwoertink** [andrewmcodes/awesome-lucky#29]
Hey @andrewmcodes! Just wanted to shoot a note to say thanks for this resource. 

We're currently working on a new section of the Lucky Website ([preview](https://github.com/luckyframework/website/pull/636)), and we will be creating a page dedicated to the links you have in this repo. Would it be ok if we used your "Awesome Lucky" logo? I'm not sure if we actually will or not, but before I go attempting it, I wanted to get your permission. 

Cheers!

**Comment by andrewmcodes** [comment]
@jwoertink howdy 👋 

Sorry for this incredibly late reply but feel free to use anything you'd like!

**Comment by jwoertink** [comment]
Sweet! https://luckyframework.org/awesome gave you a shout out too :smiley:
